name: "Infra Pipeline Kuch Bhi"

on:
  workflow_dispatch:

jobs:
  terraform-job:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 6adf1341-d89f-4adc-99ae-95fdcd50c691
          tenant-id: ecc2219a-522b-4aa8-ae49-8ad1f605b2af
          subscription-id: e32d395e-fd1a-4356-aad1-204b91db1cb4

          
